[General]
loglevel = notify
dns-server = 223.5.5.5, 119.29.29.29, system
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, localhost, *.local
exclude-simple-hostnames = true
ipv6 = false
http-listen = 0.0.0.0:8888
socks5-listen = 0.0.0.0:8889
enhanced-mode-by-rule = true

[Proxy Group]
节点选择 = select, 自动选择, 香港节点, 美国节点, 日本节点, 新加坡节点, DIRECT
自动选择 = url-test, policy-path=填写机场订阅链接, url=http://www.gstatic.com/generate_204, interval=300
香港节点 = url-test, policy-path=填写机场订阅链接, url=http://www.gstatic.com/generate_204, interval=300, policy-regex-filter=港|HK|Hong Kong
美国节点 = url-test, policy-path=填写机场订阅链接, url=http://www.gstatic.com/generate_204, interval=300, policy-regex-filter=美|US|United States
日本节点 = url-test, policy-path=填写机场订阅链接, url=http://www.gstatic.com/generate_204, interval=300, policy-regex-filter=日|JP|Japan
新加坡节点 = url-test, policy-path=填写机场订阅链接, url=http://www.gstatic.com/generate_204, interval=300, policy-regex-filter=新|SG|Singapore
AI工具 = select, 美国节点, 日本节点, 节点选择
流媒体 = select, 美国节点, 香港节点, 日本节点, 节点选择
游戏 = select, 日本节点, 香港节点, DIRECT, 节点选择
开发工具 = select, 节点选择, 自动选择, DIRECT
广告拦截 = select, REJECT
漏网之鱼 = select, 节点选择, DIRECT

[Rule]
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/reject/ads.list,广告拦截
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/reject/privacy.list,广告拦截
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/custom/my-proxy.list,节点选择
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/custom/my-direct.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/proxy/ai.list,AI工具
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/proxy/social.list,节点选择
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/proxy/streaming.list,流媒体
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/proxy/dev.list,开发工具
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/game/steam.list,游戏
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/game/blizzard.list,游戏
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/game/nintendo.list,游戏
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/direct/cn-domain.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/kyle1417/proxy-rules@main/surge/rules/direct/cn-ip.list,DIRECT
GEOIP,CN,DIRECT
FINAL,漏网之鱼
